---
kind: pipeline
name: gotag-ci

platform:
  os: linux
  arch: amd64

steps:
- name: unittest
  image: golang:1.12-stretch
  commands:
  - apt-get update && apt-get install -y -f ./third_party/*.deb
  - go vet -printf=true -unreachable=true ./*.go
  - go test -v -cover=true .
  when:
    event:
      exclude:
      - promote

...
