// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tag.proto

package mxtag_pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Value struct {
	FloatValue           *float32 `protobuf:"fixed32,1,opt,name=float_value,json=floatValue" json:"float_value,omitempty"`
	DoubleValue          *float64 `protobuf:"fixed64,2,opt,name=double_value,json=doubleValue" json:"double_value,omitempty"`
	IntValue             *int64   `protobuf:"zigzag64,3,opt,name=int_value,json=intValue" json:"int_value,omitempty"`
	UintValue            *uint64  `protobuf:"varint,4,opt,name=uint_value,json=uintValue" json:"uint_value,omitempty"`
	StrValue             *string  `protobuf:"bytes,5,opt,name=str_value,json=strValue" json:"str_value,omitempty"`
	BytesValue           []byte   `protobuf:"bytes,6,opt,name=bytes_value,json=bytesValue" json:"bytes_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Value) Reset()         { *m = Value{} }
func (m *Value) String() string { return proto.CompactTextString(m) }
func (*Value) ProtoMessage()    {}
func (*Value) Descriptor() ([]byte, []int) {
	return fileDescriptor_tag_ba2e99a0aa23a3d0, []int{0}
}
func (m *Value) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Value.Unmarshal(m, b)
}
func (m *Value) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Value.Marshal(b, m, deterministic)
}
func (dst *Value) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Value.Merge(dst, src)
}
func (m *Value) XXX_Size() int {
	return xxx_messageInfo_Value.Size(m)
}
func (m *Value) XXX_DiscardUnknown() {
	xxx_messageInfo_Value.DiscardUnknown(m)
}

var xxx_messageInfo_Value proto.InternalMessageInfo

func (m *Value) GetFloatValue() float32 {
	if m != nil && m.FloatValue != nil {
		return *m.FloatValue
	}
	return 0
}

func (m *Value) GetDoubleValue() float64 {
	if m != nil && m.DoubleValue != nil {
		return *m.DoubleValue
	}
	return 0
}

func (m *Value) GetIntValue() int64 {
	if m != nil && m.IntValue != nil {
		return *m.IntValue
	}
	return 0
}

func (m *Value) GetUintValue() uint64 {
	if m != nil && m.UintValue != nil {
		return *m.UintValue
	}
	return 0
}

func (m *Value) GetStrValue() string {
	if m != nil && m.StrValue != nil {
		return *m.StrValue
	}
	return ""
}

func (m *Value) GetBytesValue() []byte {
	if m != nil {
		return m.BytesValue
	}
	return nil
}

type Tag struct {
	Equipment            *string  `protobuf:"bytes,1,opt,name=equipment" json:"equipment,omitempty"`
	Tag                  *string  `protobuf:"bytes,2,opt,name=tag" json:"tag,omitempty"`
	AtMs                 *uint64  `protobuf:"varint,3,opt,name=at_ms,json=atMs" json:"at_ms,omitempty"`
	Value                *Value   `protobuf:"bytes,4,opt,name=value" json:"value,omitempty"`
	ValueType            *int32   `protobuf:"varint,5,opt,name=value_type,json=valueType" json:"value_type,omitempty"`
	Unit                 *string  `protobuf:"bytes,6,opt,name=unit" json:"unit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tag) Reset()         { *m = Tag{} }
func (m *Tag) String() string { return proto.CompactTextString(m) }
func (*Tag) ProtoMessage()    {}
func (*Tag) Descriptor() ([]byte, []int) {
	return fileDescriptor_tag_ba2e99a0aa23a3d0, []int{1}
}
func (m *Tag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tag.Unmarshal(m, b)
}
func (m *Tag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tag.Marshal(b, m, deterministic)
}
func (dst *Tag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tag.Merge(dst, src)
}
func (m *Tag) XXX_Size() int {
	return xxx_messageInfo_Tag.Size(m)
}
func (m *Tag) XXX_DiscardUnknown() {
	xxx_messageInfo_Tag.DiscardUnknown(m)
}

var xxx_messageInfo_Tag proto.InternalMessageInfo

func (m *Tag) GetEquipment() string {
	if m != nil && m.Equipment != nil {
		return *m.Equipment
	}
	return ""
}

func (m *Tag) GetTag() string {
	if m != nil && m.Tag != nil {
		return *m.Tag
	}
	return ""
}

func (m *Tag) GetAtMs() uint64 {
	if m != nil && m.AtMs != nil {
		return *m.AtMs
	}
	return 0
}

func (m *Tag) GetValue() *Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Tag) GetValueType() int32 {
	if m != nil && m.ValueType != nil {
		return *m.ValueType
	}
	return 0
}

func (m *Tag) GetUnit() string {
	if m != nil && m.Unit != nil {
		return *m.Unit
	}
	return ""
}

func init() {
	proto.RegisterType((*Value)(nil), "mxtag.pb.Value")
	proto.RegisterType((*Tag)(nil), "mxtag.pb.Tag")
}

func init() { proto.RegisterFile("tag.proto", fileDescriptor_tag_ba2e99a0aa23a3d0) }

var fileDescriptor_tag_ba2e99a0aa23a3d0 = []byte{
	// 259 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x90, 0xcf, 0x4a, 0xc4, 0x30,
	0x10, 0xc6, 0xc9, 0xb6, 0x95, 0x66, 0xba, 0xa0, 0xc4, 0x8b, 0xb0, 0x8a, 0x71, 0x41, 0xc8, 0xa9,
	0x07, 0xdf, 0xc3, 0xcb, 0xb0, 0x78, 0x2d, 0x29, 0xc6, 0x52, 0xe8, 0x3f, 0xdb, 0x89, 0xd8, 0xf7,
	0xf1, 0x55, 0x7c, 0xaf, 0xa5, 0x93, 0xee, 0xf6, 0xf6, 0xcd, 0xf7, 0x7d, 0x49, 0x7e, 0x13, 0x90,
	0x64, 0xab, 0x7c, 0x18, 0x7b, 0xea, 0x55, 0xda, 0xfe, 0xf2, 0x50, 0x1e, 0xff, 0x05, 0x24, 0x1f,
	0xb6, 0xf1, 0x4e, 0x3d, 0x43, 0xf6, 0xd5, 0xf4, 0x96, 0x8a, 0x9f, 0x65, 0x7c, 0x10, 0x5a, 0x98,
	0x1d, 0x02, 0x5b, 0xa1, 0xf0, 0x02, 0xfb, 0xcf, 0xde, 0x97, 0x8d, 0x5b, 0x1b, 0x3b, 0x2d, 0x8c,
	0xc0, 0x2c, 0x78, 0xa1, 0x72, 0x00, 0x59, 0x77, 0x97, 0x1b, 0x22, 0x2d, 0x8c, 0xc2, 0xb4, 0xee,
	0xd6, 0xf3, 0x4f, 0x00, 0x7e, 0x4b, 0x63, 0x2d, 0x4c, 0x8c, 0xd2, 0x5f, 0xe3, 0x03, 0xc8, 0x89,
	0xc6, 0x35, 0x4d, 0xb4, 0x30, 0x12, 0xd3, 0x89, 0xc6, 0x2b, 0x5c, 0x39, 0x93, 0x9b, 0xd6, 0xf8,
	0x46, 0x0b, 0xb3, 0x47, 0x60, 0x8b, 0x0b, 0xc7, 0x3f, 0x01, 0xd1, 0xc9, 0x56, 0xea, 0x11, 0xa4,
	0xfb, 0xf6, 0xf5, 0xd0, 0xba, 0x8e, 0x78, 0x07, 0x89, 0x9b, 0xa1, 0xee, 0x20, 0x22, 0x5b, 0x31,
	0xb9, 0xc4, 0x45, 0xaa, 0x7b, 0x48, 0x2c, 0x15, 0xed, 0xc4, 0xb4, 0x31, 0xc6, 0x96, 0xde, 0x27,
	0xf5, 0x0a, 0xc9, 0x06, 0x99, 0xbd, 0xdd, 0xe6, 0x97, 0xef, 0xca, 0xf9, 0x31, 0x0c, 0xe9, 0xb2,
	0x10, 0x8b, 0x82, 0xe6, 0x21, 0x20, 0x27, 0x28, 0xd9, 0x39, 0xcd, 0x83, 0x53, 0x0a, 0x62, 0xdf,
	0xd5, 0xc4, 0xb0, 0x12, 0x59, 0x9f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x0b, 0x90, 0x84, 0x3a, 0x84,
	0x01, 0x00, 0x00,
}
