// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tag.proto

package mxtag_pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
//const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Value struct {
	FloatValue           *float32 `protobuf:"fixed32,1,opt,name=float_value,json=floatValue" json:"float_value,omitempty"`
	DoubleValue          *float64 `protobuf:"fixed64,2,opt,name=double_value,json=doubleValue" json:"double_value,omitempty"`
	IntValue             *int64   `protobuf:"zigzag64,3,opt,name=int_value,json=intValue" json:"int_value,omitempty"`
	UintValue            *uint64  `protobuf:"varint,4,opt,name=uint_value,json=uintValue" json:"uint_value,omitempty"`
	StrValue             *string  `protobuf:"bytes,5,opt,name=str_value,json=strValue" json:"str_value,omitempty"`
	BytesValue           []byte   `protobuf:"bytes,6,opt,name=bytes_value,json=bytesValue" json:"bytes_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Value) Reset()         { *m = Value{} }
func (m *Value) String() string { return proto.CompactTextString(m) }
func (*Value) ProtoMessage()    {}
func (*Value) Descriptor() ([]byte, []int) {
	return fileDescriptor_27f545bcde37ecb5, []int{0}
}

func (m *Value) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Value.Unmarshal(m, b)
}
func (m *Value) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Value.Marshal(b, m, deterministic)
}
func (m *Value) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Value.Merge(m, src)
}
func (m *Value) XXX_Size() int {
	return xxx_messageInfo_Value.Size(m)
}
func (m *Value) XXX_DiscardUnknown() {
	xxx_messageInfo_Value.DiscardUnknown(m)
}

var xxx_messageInfo_Value proto.InternalMessageInfo

func (m *Value) GetFloatValue() float32 {
	if m != nil && m.FloatValue != nil {
		return *m.FloatValue
	}
	return 0
}

func (m *Value) GetDoubleValue() float64 {
	if m != nil && m.DoubleValue != nil {
		return *m.DoubleValue
	}
	return 0
}

func (m *Value) GetIntValue() int64 {
	if m != nil && m.IntValue != nil {
		return *m.IntValue
	}
	return 0
}

func (m *Value) GetUintValue() uint64 {
	if m != nil && m.UintValue != nil {
		return *m.UintValue
	}
	return 0
}

func (m *Value) GetStrValue() string {
	if m != nil && m.StrValue != nil {
		return *m.StrValue
	}
	return ""
}

func (m *Value) GetBytesValue() []byte {
	if m != nil {
		return m.BytesValue
	}
	return nil
}

type Tag struct {
	Equipment            *string  `protobuf:"bytes,1,opt,name=equipment" json:"equipment,omitempty"`
	Tag                  *string  `protobuf:"bytes,2,opt,name=tag" json:"tag,omitempty"`
	AtMs                 *uint64  `protobuf:"varint,3,opt,name=at_ms,json=atMs" json:"at_ms,omitempty"`
	Value                *Value   `protobuf:"bytes,4,opt,name=value" json:"value,omitempty"`
	ValueType            *int32   `protobuf:"varint,5,opt,name=value_type,json=valueType" json:"value_type,omitempty"`
	Unit                 *string  `protobuf:"bytes,6,opt,name=unit" json:"unit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tag) Reset()         { *m = Tag{} }
func (m *Tag) String() string { return proto.CompactTextString(m) }
func (*Tag) ProtoMessage()    {}
func (*Tag) Descriptor() ([]byte, []int) {
	return fileDescriptor_27f545bcde37ecb5, []int{1}
}

func (m *Tag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tag.Unmarshal(m, b)
}
func (m *Tag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tag.Marshal(b, m, deterministic)
}
func (m *Tag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tag.Merge(m, src)
}
func (m *Tag) XXX_Size() int {
	return xxx_messageInfo_Tag.Size(m)
}
func (m *Tag) XXX_DiscardUnknown() {
	xxx_messageInfo_Tag.DiscardUnknown(m)
}

var xxx_messageInfo_Tag proto.InternalMessageInfo

func (m *Tag) GetEquipment() string {
	if m != nil && m.Equipment != nil {
		return *m.Equipment
	}
	return ""
}

func (m *Tag) GetTag() string {
	if m != nil && m.Tag != nil {
		return *m.Tag
	}
	return ""
}

func (m *Tag) GetAtMs() uint64 {
	if m != nil && m.AtMs != nil {
		return *m.AtMs
	}
	return 0
}

func (m *Tag) GetValue() *Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Tag) GetValueType() int32 {
	if m != nil && m.ValueType != nil {
		return *m.ValueType
	}
	return 0
}

func (m *Tag) GetUnit() string {
	if m != nil && m.Unit != nil {
		return *m.Unit
	}
	return ""
}

type RequestData struct {
	Module               *string  `protobuf:"bytes,1,opt,name=module" json:"module,omitempty"`
	Device               *string  `protobuf:"bytes,2,opt,name=device" json:"device,omitempty"`
	Name                 *string  `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestData) Reset()         { *m = RequestData{} }
func (m *RequestData) String() string { return proto.CompactTextString(m) }
func (*RequestData) ProtoMessage()    {}
func (*RequestData) Descriptor() ([]byte, []int) {
	return fileDescriptor_27f545bcde37ecb5, []int{2}
}

func (m *RequestData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestData.Unmarshal(m, b)
}
func (m *RequestData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestData.Marshal(b, m, deterministic)
}
func (m *RequestData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestData.Merge(m, src)
}
func (m *RequestData) XXX_Size() int {
	return xxx_messageInfo_RequestData.Size(m)
}
func (m *RequestData) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestData.DiscardUnknown(m)
}

var xxx_messageInfo_RequestData proto.InternalMessageInfo

func (m *RequestData) GetModule() string {
	if m != nil && m.Module != nil {
		return *m.Module
	}
	return ""
}

func (m *RequestData) GetDevice() string {
	if m != nil && m.Device != nil {
		return *m.Device
	}
	return ""
}

func (m *RequestData) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

type Request struct {
	Method               *string        `protobuf:"bytes,1,opt,name=method" json:"method,omitempty"`
	List                 []*RequestData `protobuf:"bytes,2,rep,name=list" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_27f545bcde37ecb5, []int{3}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetMethod() string {
	if m != nil && m.Method != nil {
		return *m.Method
	}
	return ""
}

func (m *Request) GetList() []*RequestData {
	if m != nil {
		return m.List
	}
	return nil
}

type Response struct {
	Method               *string  `protobuf:"bytes,1,opt,name=method" json:"method,omitempty"`
	List                 []*Tag   `protobuf:"bytes,2,rep,name=list" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_27f545bcde37ecb5, []int{4}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetMethod() string {
	if m != nil && m.Method != nil {
		return *m.Method
	}
	return ""
}

func (m *Response) GetList() []*Tag {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterType((*Value)(nil), "mxtag.pb.Value")
	proto.RegisterType((*Tag)(nil), "mxtag.pb.Tag")
	proto.RegisterType((*RequestData)(nil), "mxtag.pb.RequestData")
	proto.RegisterType((*Request)(nil), "mxtag.pb.Request")
	proto.RegisterType((*Response)(nil), "mxtag.pb.Response")
}

func init() { proto.RegisterFile("tag.proto", fileDescriptor_27f545bcde37ecb5) }

var fileDescriptor_27f545bcde37ecb5 = []byte{
	// 361 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0x4d, 0x8e, 0xd3, 0x40,
	0x10, 0x85, 0xd5, 0xb1, 0x1d, 0xdc, 0xe5, 0x20, 0x50, 0x23, 0x50, 0xa4, 0x80, 0x70, 0x2c, 0x21,
	0x99, 0x4d, 0x16, 0x39, 0x03, 0xec, 0x60, 0x41, 0x29, 0x62, 0x1b, 0x75, 0x70, 0xe3, 0xb1, 0xe4,
	0xbf, 0xa4, 0xab, 0xa3, 0xc9, 0x7d, 0xe6, 0x2a, 0x73, 0xaf, 0x91, 0xcb, 0x9d, 0x78, 0x66, 0x31,
	0xbb, 0xaa, 0xf7, 0x9e, 0x9f, 0xbf, 0x6a, 0x90, 0xa4, 0xcb, 0x4d, 0x7f, 0xea, 0xa8, 0x53, 0x71,
	0x73, 0xcf, 0xcb, 0x21, 0x7b, 0x14, 0x10, 0xfd, 0xd5, 0xb5, 0x33, 0xea, 0x2b, 0x24, 0xff, 0xeb,
	0x4e, 0xd3, 0xfe, 0x3c, 0xac, 0x4b, 0x91, 0x8a, 0x7c, 0x86, 0xc0, 0xd2, 0x18, 0x58, 0xc3, 0xa2,
	0xe8, 0xdc, 0xa1, 0x36, 0x3e, 0x31, 0x4b, 0x45, 0x2e, 0x30, 0x19, 0xb5, 0x31, 0xb2, 0x02, 0x59,
	0xb5, 0xd7, 0x86, 0x20, 0x15, 0xb9, 0xc2, 0xb8, 0x6a, 0xfd, 0xf7, 0x5f, 0x00, 0xdc, 0xe4, 0x86,
	0xa9, 0xc8, 0x43, 0x94, 0xee, 0x66, 0xaf, 0x40, 0x5a, 0x3a, 0x79, 0x37, 0x4a, 0x45, 0x2e, 0x31,
	0xb6, 0x74, 0xba, 0xc1, 0x1d, 0x2e, 0x64, 0xac, 0xb7, 0xe7, 0xa9, 0xc8, 0x17, 0x08, 0x2c, 0x71,
	0x20, 0x7b, 0x10, 0x10, 0xec, 0x74, 0xa9, 0x3e, 0x83, 0x34, 0x47, 0x57, 0xf5, 0x8d, 0x69, 0x89,
	0x6f, 0x90, 0x38, 0x09, 0xea, 0x3d, 0x04, 0xa4, 0x4b, 0x26, 0x97, 0x38, 0x8c, 0xea, 0x03, 0x44,
	0x9a, 0xf6, 0x8d, 0x65, 0xda, 0x10, 0x43, 0x4d, 0xbf, 0xad, 0xfa, 0x06, 0xd1, 0x04, 0x99, 0x6c,
	0xdf, 0x6d, 0xae, 0xcf, 0xb5, 0xe1, 0x9f, 0xe1, 0xe8, 0x0e, 0x07, 0xf1, 0xb0, 0xa7, 0x4b, 0x3f,
	0x22, 0x47, 0x28, 0x59, 0xd9, 0x5d, 0x7a, 0xa3, 0x14, 0x84, 0xae, 0xad, 0x88, 0x61, 0x25, 0xf2,
	0x9c, 0xfd, 0x81, 0x04, 0xcd, 0xd1, 0x19, 0x4b, 0x3f, 0x34, 0x69, 0xf5, 0x09, 0xe6, 0x4d, 0x57,
	0xb8, 0xda, 0x78, 0x54, 0xbf, 0x0d, 0x7a, 0x61, 0xce, 0xd5, 0x3f, 0xe3, 0x51, 0xfd, 0x36, 0x54,
	0xb6, 0xba, 0x19, 0x9f, 0x56, 0x22, 0xcf, 0xd9, 0x2f, 0x78, 0xe3, 0x2b, 0xb9, 0xce, 0xd0, 0x5d,
	0x57, 0xdc, 0xea, 0x78, 0x53, 0xdf, 0x21, 0xac, 0x2b, 0x4b, 0xcb, 0x59, 0x1a, 0xe4, 0xc9, 0xf6,
	0xe3, 0x74, 0xce, 0x33, 0x16, 0xe4, 0x48, 0xf6, 0x13, 0x62, 0x34, 0xb6, 0xef, 0x5a, 0x6b, 0x5e,
	0xad, 0x5b, 0xbf, 0xa8, 0x7b, 0x3b, 0xd5, 0xed, 0x74, 0x39, 0xd6, 0x3c, 0x05, 0x00, 0x00, 0xff,
	0xff, 0x8e, 0x6d, 0xf8, 0xf9, 0x6c, 0x02, 0x00, 0x00,
}
